// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
//
// --------------------------------------------------------------------------
// $Maintainer: Mohammed Alhigaylan $
// $Authors: Mohammed Alhigaylan $
// --------------------------------------------------------------------------

#include <OpenMS/ANALYSIS/ID/FalseDiscoveryRate.h>
#include <OpenMS/ANALYSIS/ID/SimpleSearchEngineAlgorithm.h>
#include <OpenMS/APPLICATIONS/TOPPBase.h>

#include <OpenMS/FORMAT/FileHandler.h>
#include <OpenMS/KERNEL/StandardTypes.h>
#include <OpenMS/SYSTEM/File.h>

#include <fstream>

#ifdef _OPENMP
  #include <omp.h>
#endif


using namespace OpenMS;
using namespace std;

//-------------------------------------------------------------
//Doxygen docu
//-------------------------------------------------------------

/**
@page TOPP_SpokeML SpokeML

@brief Identifies peptides in pseudo MS/MS spectra generated by diaWeaver.

<CENTER>
    <table>
        <tr>
            <th ALIGN = "center"> pot. predecessor tools </td>
            <td VALIGN="middle" ROWSPAN=2> &rarr; SpokeML &rarr;</td>
            <th ALIGN = "center"> pot. successor tools </td>
        </tr>
        <tr>
            <td VALIGN="middle" ALIGN = "center" ROWSPAN=1> @ref TOPP_diaWeaver</td>
            <td VALIGN="middle" ALIGN = "center" ROWSPAN=1> @ref TOPP_IDFilter or @n any protein/peptide processing tool</td>
        </tr>
    </table>
</CENTER>

@note Currently mzIdentML (mzid) is not directly supported as an input/output format of this tool. Convert mzid files to/from idXML using @ref TOPP_IDFileConverter if necessary.

<B>The command line parameters of this tool are:</B>
@verbinclude TOPP_SpokeML.cli
<B>INI file documentation of this tool:</B>
@htmlinclude TOPP_SpokeML.html
*/

// We do not want this class to show up in the docu:
/// @cond TOPPCLASSES


class SpokeML :
    public TOPPBase
{
  public:
    SpokeML() :
      TOPPBase("SpokeML",
        "Identifies peptides in pseudo MS/MS spectra generated by diaWeaver.",
        true)
    {
    }

  protected:
    void registerOptionsAndFlags_() override
    {
      registerInputFile_("in", "<file>", "", "Input pseudo spectra file (mzML) from diaWeaver.");
      setValidFormats_("in", ListUtils::create<String>("mzML"));

      registerInputFile_("database", "<file>", "", "Protein sequence database.");
      setValidFormats_("database", ListUtils::create<String>("fasta"));

      registerOutputFile_("out", "<file>", "", "Output TSV with target/decoy sequence pairs per spectrum.");
      setValidFormats_("out", ListUtils::create<String>("tsv"));

      // put search algorithm parameters at Search: subtree of parameters
      // default top_hits is raised to 10 so both target and decoy candidates are captured per spectrum
      Param search_algo_params_with_subsection;
      search_algo_params_with_subsection.insert("Search:", SimpleSearchEngineAlgorithm().getDefaults());
      search_algo_params_with_subsection.setValue("Search:report:top_hits", 10);
      registerFullParam_(search_algo_params_with_subsection);

      // FDR parameters
      Param fdr_params_with_subsection;
      fdr_params_with_subsection.insert("FDR:", FalseDiscoveryRate().getDefaults());
      registerFullParam_(fdr_params_with_subsection);

      registerDoubleOption_("FDR:PSM_threshold", "<value>", 0.01, "q-value threshold for PSM-level FDR filtering.", false);
      setMinFloat_("FDR:PSM_threshold", 0.0);
      setMaxFloat_("FDR:PSM_threshold", 1.0);
    }

    ExitCodes main_(int, const char**) override
    {
      String in = getStringOption_("in");
      String database = getStringOption_("database");
      String out = getStringOption_("out");

      vector<ProteinIdentification> protein_ids;
      PeptideIdentificationList peptide_ids;

      SimpleSearchEngineAlgorithm sse;
      sse.setParameters(getParam_().copy("Search:", true));
      SimpleSearchEngineAlgorithm::ExitCodes e = sse.search(in, database, protein_ids, peptide_ids);
      if (e != SimpleSearchEngineAlgorithm::ExitCodes::EXECUTION_OK)
      {
        return TOPPBase::ExitCodes::INTERNAL_ERROR;
      }

      FalseDiscoveryRate fdr;
      fdr.setParameters(getParam_().copy("FDR:", true));
      fdr.applyBasic(protein_ids, peptide_ids);

      // Filter PSMs at FDR threshold and retain top target + top decoy hit per passing PSM.
      // After applyBasic, the score is q-value (lower is better) and hits are sorted accordingly.
      double fdr_threshold = getDoubleOption_("FDR:PSM_threshold");
      PeptideIdentificationList filtered_ids;
      for (auto& pi : peptide_ids)
      {
        if (pi.getHits().empty()) continue;
        if (pi.getHits()[0].getScore() > fdr_threshold) continue;

        PeptideHit* top_target = nullptr;
        PeptideHit* top_decoy = nullptr;
        for (auto& hit : pi.getHits())
        {
          String td = hit.getMetaValue("target_decoy").toString();
          if (!top_target && (td == "target" || td == "target+decoy"))
          {
            top_target = &hit;
          }
          else if (!top_decoy && td == "decoy")
          {
            top_decoy = &hit;
          }
          if (top_target && top_decoy) break;
        }

        if (!top_target || !top_decoy) continue;

        pi.setHits({*top_target, *top_decoy});
        filtered_ids.push_back(pi);
      }
      peptide_ids = std::move(filtered_ids);

      std::ofstream out_tsv(out);
      out_tsv << "spectrum_index\ttarget_sequence\tdecoy_sequence\n";
      for (const auto& pi : peptide_ids)
      {
        const String target_seq = pi.getHits()[0].getSequence().toString();
        const String decoy_seq  = pi.getHits()[1].getSequence().toString();
        out_tsv << pi.getSpectrumRef() << "\t" << target_seq << "\t" << decoy_seq << "\n";
      }

      return EXECUTION_OK;
    }

};

int main(int argc, const char** argv)
{
  SpokeML tool;
  return tool.main(argc, argv);
}

///@endcond
