// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
//
// --------------------------------------------------------------------------
// $Maintainer: Mohammed Alhigaylan $
// $Authors: Mohammed Alhigaylan $
// --------------------------------------------------------------------------

#include <OpenMS/ANALYSIS/ID/FalseDiscoveryRate.h>
#include <OpenMS/ANALYSIS/ID/SimpleSearchEngineAlgorithm.h>
#include <OpenMS/APPLICATIONS/TOPPBase.h>

#include <OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h>
#include <OpenMS/CONCEPT/Constants.h>
#include <OpenMS/FORMAT/FileHandler.h>
#include <OpenMS/KERNEL/MSExperiment.h>
#include <OpenMS/KERNEL/StandardTypes.h>
#include <OpenMS/SYSTEM/File.h>

#include <cmath>
#include <fstream>

#ifdef _OPENMP
  #include <omp.h>
#endif


using namespace OpenMS;
using namespace std;

//-------------------------------------------------------------
//Doxygen docu
//-------------------------------------------------------------

/**
@page TOPP_SpokeML SpokeML

@brief Identifies peptides in pseudo MS/MS spectra generated by diaWeaver.

<CENTER>
    <table>
        <tr>
            <th ALIGN = "center"> pot. predecessor tools </td>
            <td VALIGN="middle" ROWSPAN=2> &rarr; SpokeML &rarr;</td>
            <th ALIGN = "center"> pot. successor tools </td>
        </tr>
        <tr>
            <td VALIGN="middle" ALIGN = "center" ROWSPAN=1> @ref TOPP_diaWeaver</td>
            <td VALIGN="middle" ALIGN = "center" ROWSPAN=1> @ref TOPP_IDFilter or @n any protein/peptide processing tool</td>
        </tr>
    </table>
</CENTER>

@note Currently mzIdentML (mzid) is not directly supported as an input/output format of this tool. Convert mzid files to/from idXML using @ref TOPP_IDFileConverter if necessary.

<B>The command line parameters of this tool are:</B>
@verbinclude TOPP_SpokeML.cli
<B>INI file documentation of this tool:</B>
@htmlinclude TOPP_SpokeML.html
*/

// We do not want this class to show up in the docu:
/// @cond TOPPCLASSES


class SpokeML :
    public TOPPBase
{
  public:
    SpokeML() :
      TOPPBase("SpokeML",
        "Identifies peptides in pseudo MS/MS spectra generated by diaWeaver.",
        true)
    {
    }

  protected:
    void registerOptionsAndFlags_() override
    {
      registerInputFile_("in", "<file>", "", "Input pseudo spectra file (mzML) from diaWeaver.");
      setValidFormats_("in", ListUtils::create<String>("mzML"));

      registerInputFile_("database", "<file>", "", "Protein sequence database.");
      setValidFormats_("database", ListUtils::create<String>("fasta"));

      registerOutputFile_("out", "<file>", "", "Output TSV with target/decoy sequence pairs per spectrum.");
      setValidFormats_("out", ListUtils::create<String>("tsv"));

      // put search algorithm parameters at Search: subtree of parameters
      // default top_hits is raised to 10 so both target and decoy candidates are captured per spectrum
      Param search_algo_params_with_subsection;
      search_algo_params_with_subsection.insert("Search:", SimpleSearchEngineAlgorithm().getDefaults());
      search_algo_params_with_subsection.setValue("Search:report:top_hits", 10);
      search_algo_params_with_subsection.setValue("Search:decoys", "true");
      registerFullParam_(search_algo_params_with_subsection);

      // FDR parameters
      Param fdr_params_with_subsection;
      fdr_params_with_subsection.insert("FDR:", FalseDiscoveryRate().getDefaults());
      fdr_params_with_subsection.setValue("FDR:add_decoy_peptides", "true");
      registerFullParam_(fdr_params_with_subsection);

      registerDoubleOption_("FDR:PSM_threshold", "<value>", 0.01, "q-value threshold for PSM-level FDR filtering.", false);
      setMinFloat_("FDR:PSM_threshold", 0.0);
      setMaxFloat_("FDR:PSM_threshold", 1.0);
    }

    ExitCodes main_(int, const char**) override
    {
      String in = getStringOption_("in");
      String database = getStringOption_("database");
      String out = getStringOption_("out");

      vector<ProteinIdentification> protein_ids;
      PeptideIdentificationList peptide_ids;

      SimpleSearchEngineAlgorithm sse;
      sse.setParameters(getParam_().copy("Search:", true));
      SimpleSearchEngineAlgorithm::ExitCodes e = sse.search(in, database, protein_ids, peptide_ids);
      if (e != SimpleSearchEngineAlgorithm::ExitCodes::EXECUTION_OK)
      {
        return TOPPBase::ExitCodes::INTERNAL_ERROR;
      }

      FalseDiscoveryRate fdr;
      fdr.setParameters(getParam_().copy("FDR:", true));
      fdr.applyBasic(protein_ids, peptide_ids);

      // Filter PSMs at FDR threshold and retain top target + top decoy hit per passing PSM.
      // After applyBasic, the score is q-value (lower is better) and hits are sorted accordingly.
      double fdr_threshold = getDoubleOption_("FDR:PSM_threshold");
      PeptideIdentificationList filtered_ids;
      for (auto& pi : peptide_ids)
      {
        if (pi.getHits().empty()) continue;
        if (pi.getHits()[0].getScore() > fdr_threshold) continue;

        PeptideHit* top_target = nullptr;
        PeptideHit* top_decoy = nullptr;
        for (auto& hit : pi.getHits())
        {
          String td = hit.getMetaValue("target_decoy").toString();
          if (!top_target && (td == "target" || td == "target+decoy"))
          {
            top_target = &hit;
          }
          else if (!top_decoy && td == "decoy")
          {
            top_decoy = &hit;
          }
          if (top_target && top_decoy) break;
        }

        if (!top_target || !top_decoy) continue;

        pi.setHits({*top_target, *top_decoy});
        filtered_ids.push_back(pi);
      }
      peptide_ids = std::move(filtered_ids);

      // Load experimental spectra for ion matching
      PeakMap exp;
      FileHandler().loadExperiment(in, exp, {FileTypes::MZML});

      // Build native ID -> spectrum map for fast lookup
      std::map<String, const MSSpectrum*> native_id_to_spec;
      for (const auto& spec : exp)
      {
        native_id_to_spec[spec.getNativeID()] = &spec;
      }

      // Configure TheoreticalSpectrumGenerator for b/y ions only
      TheoreticalSpectrumGenerator tsg;
      Param tsg_params = tsg.getDefaults();
      tsg_params.setValue("add_b_ions", "true");
      tsg_params.setValue("add_y_ions", "true");
      tsg_params.setValue("add_a_ions", "false");
      tsg_params.setValue("add_c_ions", "false");
      tsg_params.setValue("add_x_ions", "false");
      tsg_params.setValue("add_z_ions", "false");
      tsg_params.setValue("add_metainfo", "true");
      tsg.setParameters(tsg_params);

      const double ppm_tolerance = 20.0;

      std::ofstream out_tsv(out);
      out_tsv << "spectrum_index\tsequence\ttype\tfragment_label\t"
              << "pearson_score\txcorr_lag_intensity\tdelta_rt\tdelta_im\n";

      // For each theoretical b/y ion that matches in exp_spec within ppm_tolerance,
      // writes one row to out_tsv with the ion's scores from the diaWeaver FloatDataArrays.
      // used_peaks tracks experimental peak indices already claimed by the target; decoy
      // is barred from reusing them.
      auto writeMatchedIons = [&](const AASequence& seq, const MSSpectrum& exp_spec,
                                  const String& spec_ref, const String& type,
                                  std::set<Int>& used_peaks)
      {
        PeakSpectrum theo;
        tsg.getSpectrum(theo, seq, 1, 2);

        const MSSpectrum::StringDataArray* ion_names = nullptr;
        for (const auto& sda : theo.getStringDataArrays())
        {
          if (sda.getName() == Constants::UserParam::IonNames)
          {
            ion_names = &sda;
            break;
          }
        }
        if (!ion_names) return;

        for (Size i = 0; i < theo.size(); ++i)
        {
          const double mz  = theo[i].getMZ();
          const double tol = mz * ppm_tolerance * 1e-6;
          const Int exp_idx = exp_spec.findNearest(mz, tol);
          if (exp_idx == -1) continue;
          if (used_peaks.count(exp_idx)) continue;

          if (type == "target") used_peaks.insert(exp_idx);

          double pearson = 0.0, xcorr = 0.0, frt = 0.0, fim = 0.0;
          for (const auto& fda : exp_spec.getFloatDataArrays())
          {
            if      (fda.getName() == "pearson_score")         pearson = fda[exp_idx];
            else if (fda.getName() == "xcorr_lag_intensity")   xcorr   = fda[exp_idx];
            else if (fda.getName() == "fragment_rt")           frt     = fda[exp_idx];
            else if (fda.getName() == "fragment_ion_mobility") fim     = fda[exp_idx];
          }

          const double delta_rt = std::abs(frt - exp_spec.getRT());
          const double delta_im = std::abs(fim - exp_spec.getDriftTime());

          out_tsv << spec_ref          << "\t"
                  << seq.toString()    << "\t"
                  << type              << "\t"
                  << (*ion_names)[i]   << "\t"
                  << pearson           << "\t"
                  << xcorr             << "\t"
                  << delta_rt          << "\t"
                  << delta_im          << "\n";
        }
      };

      for (const auto& pi : peptide_ids)
      {
        auto spec_it = native_id_to_spec.find(pi.getSpectrumReference());
        if (spec_it == native_id_to_spec.end()) continue;

        const MSSpectrum& exp_spec = *spec_it->second;
        const String spec_ref = pi.getSpectrumReference();

        std::set<Int> used_peaks;
        writeMatchedIons(pi.getHits()[0].getSequence(), exp_spec, spec_ref, "target", used_peaks);
        writeMatchedIons(pi.getHits()[1].getSequence(), exp_spec, spec_ref, "decoy", used_peaks);
      }

      return EXECUTION_OK;
    }

};

int main(int argc, const char** argv)
{
  SpokeML tool;
  return tool.main(argc, argv);
}

///@endcond
